services:
  - name: mongo:4.2
    alias: mongo

stages:
  - test
  - publish

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  untracked: false
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

default:
  image: registry.gitlab.com/medicines-discovery-catapult/informatics/docker-images/ci/sbt:latest

test:
  stage: test
  variables:
    MONGO_HOST: mongo
    MONGO_PORT: 27017
    MONGO_USERNAME: admin
    MONGO_PASSWORD: admin
  script:
    - sbt +clean coverage it/test coverageReport
  coverage: /Coverage was \[\d+.\d+\%\]/

publish-snapshot:
  stage: publish
  script:
    - sbt +publish
  except:
    refs:
      - main
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-master:
  stage: publish
  script:
    - cictl exec release sbt
  only:
    - main
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
